language: node_js
node_js:
  - "0.12.0"

sudo: false

before_script:
    - npm install

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "TqryAZJrP2xT/lj5j0kqs8UHhZorMUwEVcWAIcTBl23+bQXLDUnNNFcMxTojhJU3a3/CJilbQ+6MwwZWmZyOZeQ043ZcxFy0dFIHcXD61R0uAeOZYPqC+69ufk1RollSbIvt4emXGmuffWLNKNKmW/SKh+ObMY/vY9PUbrIGd/xYYRO6kwablbWTGc8+rg3CW57lH2ZPJ5iQb2J4XuM4I5Y/nus3hd1iULwlG1fN3mwOfr2jYObI5igYVwiV6pZMiCPBukxBuit8rmbqm2emCBkwWktDjwxNoMhwX7dcvEbb6N6jrMy/kELdI5m6xTlIdV9vAWIRATCma/eYfqhzJ3X001QWHC9SU7hXde8WBHl/WU3rfSOvu9pVHoDzCg3aBHdM5nJ5yIxOdJiconOa98YxMSjJF5/4Au05vCte0hUJRK2Zf/Eo3Sq2Aj94kZwcqp0NRndMyBYQPBqfR/CglUBvdzkDQpOycvkBZF0167sB8J80erfDhEyZKSqart10Pju9Fq3rH/JR/gVJZvTGu1XOvekd/99nhgrIt5Qz0u5/JG6hqS/k7FnaSVclDjwa+vl2uNT/WTU8eZ/LsisElNeWqLKBpe6J6Qk58P7QwsiBVVQgm8FkV3E9AU2bKYmNoHLnXRHmEFbTTo9zJoqxl5G7EszXA0FcvyDQcEWFdzY="
  secret_access_key:
    secure: "RCFUHjJHkSZWCRjdVEDM6KetUQxJ66UnVHdjX5e4Md1gCGpQw4TNgXXlGEesDVD7s2c6VRGMKgNEF7ctcJVpYDMVwwHx8ZqKm8GtN99ggnJJ/UDou+wa4GB/UfTnvmqNJ5Y0MNT0TmcwMxHeEwZzEb+fvJrrwGFr8oVR+R1wmaeVENo83fcD1C387NhuOVCVXuWMcYR8tAzTrc+tjbdFmDFoGAHDKTuj46ucEYWTOFn+0PzwvYxlyGaZ+wMKw/zXl4hKGRcwnUXbCXVAreJ8uAH2uCw+ep6oVEt3gd1/vZqh52fHtIIdmm+aRHg+YPsDaQ8bcrDae6W6AMeEp34Hn5/Qv033AChAILoWzdruRjbC/5TwA4PWOnoFsyBKFSsqtZw2lLGlCV5pw2Bh1TNMXQNOQke3HGWUHwajDpbkM1ih99hyqFca+ehN8AdJ04/tKnv4mxo/0sMsafUrEQL1GRF9si7IesqeSoQu6XEqvvKELi88wB5wRyjzqEA/a8avEgtUesNrrRAwm2270xboXOiqlqB1FmhwBiTT5ir0H8DztaRC5bW16iNWqZXnrScnkSMp5KiuYI5vGHBh0JjyM7MBypS2PLUX3DT0WxmjuNTtRQmxDTdFRbQHTHzFExj0ucoUEN6WNSNSv+DBF6R68nsARZrqYI7Sl8pn4qcMLeQ="
  region: us-east-1
  app: ghost
  env: ghost-ci
  bucket_name:
    secure: "mTHKTxV+xIIkZajnKMLjxNChQfiklkyOoA5sv/T9XDf8oUYJXGuYs2OL0dHzNPVOWhjRbw27WyNYHD/qAZU97XtCq7VwceWIyynpExVETglElSagIsMlfGFBupt1/r02VjlKO9ADkILZte5Pn3v1YhsKp5/WY3SZtUMTzjFDUUMM3ZrPeYewbjK9KbkUvQmkeiU27voJs8JsHjIYsuDD9E2I/n0Kurwq/9/O0P78nC5yDz/X39YvDJhK2Q+EnRN6PcL31paWiUa1zP6Mm5hlYCoN1/9Rr0DMKSGyiL6eMMJPU0DMRLX/SuUIBW6gNaBMF8PBldUvTLJOE8VRF6NlJnk8RIP6s4zihrNaZQJq4knr+5rsWOeL32Q2AYMKpgzuxmUSDvX7M7VX17x6ZHIeObka0gZ2g3a+hVbHXpCPSo8mQIPPpExp+/ym8vgOdnF8InY1ib/Ni8q0gFp/RSMK4+nOkmooym9Pfcvq9D4FYYhOcnMP6ty+PHyZbHG75OXn3JKpKa0slXosDD+bykp4qQIfw0JpGNSwKn3sVMyAE6dIOhZNQYgzZvaF1hJOqU2UmbZvc0pxO4AJeaSkaUBSw5j//16ShaCanNpzUxcsLWohEsJhsFZj9m2NrFMjKN1oKTfolwPe8t0RnalwF5fdGgJg8t4I/ytJijx14PHlm+I="
  on:
    repo: justmiles/ghost
    branch: master
